### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by epoddubny** [StephenOTT/camunda-prometheus-process-engine-plugin#31]
After adding camunda-prometheus-process-engine-plugin I noticed that my application uses a lot of memory. 2 GB RAM instead of 400 MB before. Then I took heap dump and discovered that 80% memory uses ProcessInstances.groovy

```XML
<dependency>
    <groupId>com.github.StephenOTT</groupId>
    <artifactId>camunda-prometheus-process-engine-plugin</artifactId>
    <version>1.7.2</version>
</dependency>
```

```YML
system:
- collector: io.digitalstate.camunda.prometheus.collectors.camunda.BpmnExecution
  enable: true
  startDate: now
  endDate: now
  startDelay: 60000
  frequency: 300000
- collector: io.digitalstate.camunda.prometheus.collectors.camunda.JobExecutor
  enable: true
  startDate: now
  endDate: now
  startDelay: 60000
  frequency: 300000
custom:
  - collector: classpath:/prometheus/customcollectors/ProcessInstances.groovy
    enable: true
    startDelay: 60000
    frequency: 300000
  - collector: classpath:/prometheus/customcollectors/TimerMetrics.groovy
    enable: true
    startDelay: 60000
    frequency: 300000
  - collector: classpath:/prometheus/customcollectors/IncidentMetricsRuntime.groovy
    enable: true
    startDelay: 60000
    frequency: 300000

```

<img width="1412" alt="01" src="https://user-images.githubusercontent.com/11692134/75718509-20c06500-5ce4-11ea-80df-59b0531bb1c7.png">
